### ISSUE TITLE
Can't have separate outmaps for both shader types residing in the same file

### ISSUE THREAD

**Issue by DiscostewSM** [smealum/aemstro#7]
Currently, the ".out" lines affects both the vertex and geometry shaders in the same file, resulting in some unnecessary, and problematic, code to be used when going from vertex to geometry. A vertex shader could send 2 outputs to the geometry shader, but the geometry shader may send 3 outputs to later stages. Right now, the only way the two shader types could work together with different outmaps  is if both are in separate files.

Would it be too much trouble if the directive ".out" could be split so we can work with ".vout" and ".gout"?

**Comment by smealum** [comment]
no point. when you throw a geoshader in the mix the vertex shader's output is devoid of semantics from the gpu's pov.
